### ISSUE TITLE
Main discussion

### ISSUE THREAD

**Issue by romandrahan** [instrumentisto/vue-app-example#1]
## Lazy Loading (through Webpack)
https://router.vuejs.org/en/advanced/lazy-loading.html
https://vuejs.org/v2/guide/components.html#Async-Components
https://webpack.js.org/guides/code-splitting-require/
https://github.com/TypeStrong/ts-loader#loading-other-resources-and-code-splitting

**Comment by romandragan** [comment]
## Lazy Loading

https://router.vuejs.org/en/advanced/lazy-loading.html
https://webpack.js.org/guides/code-splitting-require/
https://github.com/TypeStrong/ts-loader#loading-other-resources-and-code-splitting

**Comment by romandrahan** [comment]
## Routing

https://router.vuejs.org/en/essentials/getting-started.html

**Comment by romandrahan** [comment]
## Webpack

https://shellmonger.com/2016/01/22/working-with-fonts-with-webpack/
https://medium.com/@victorleungtw/how-to-use-webpack-with-react-and-bootstrap-b94d33765970#.o7yf81lwi
https://habrahabr.ru/post/265801/
https://www.npmjs.com/package/html-webpack-plugin

**Comment by romandrahan** [comment]
## State

https://vuejs.org/v2/guide/state-management.html
http://vuex.vuejs.org/en/getting-started.html
https://alligator.io/vuejs/intro-to-vuex/

**Comment by romandrahan** [comment]
@tyranron, what do you think if we will integrate https://vuetifyjs.com/ into our test app? It's something like Bootstrap, https://vuetifyjs.com/ etc. It's will be very useful for our  admin/management pages.
